### ISSUE TITLE
Some alerts not working

### ISSUE THREAD

**Issue by stxyzth** [mgmoerman/docs#1]
Thanks again for the write up, helps a lot considering Observium doesn't have one.

I used the processor above 80% one but that doesn't pull anything, even though there are processors on there.

The memory one works however I only want to monitor "Physical Memory" - how would I do that?

**Comment by mgmoerman** [comment]
Hi,

You could use something like "mempool_descr match Physical*" in the entity match field, check also the attributes and such in the document.

Not sure what you mean by "doesn't pull anything", care to explain?
